### PR TITLE
Update Fredesktop-sdk to 20.08

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Did this remove the arm (32 bit) build?

**Comment by A6GibKm** [comment]
Not really, but close, I think 20.08 does not do 32 bit builds. The 32bit builds were removed at some prior point.

**Comment by MarcoFalke** [comment]
We used to have `arm` builds (still in the json), but they are no longer built

**Comment by A6GibKm** [comment]
My bad, 20.08 indeed removed all 32bit builds.

**Comment by MarcoFalke** [comment]
assuming that we'll have to bump to 20.08 eventually, it could make sense to remove the arm explicitly. Otherwise, maybe revert?

**Comment by A6GibKm** [comment]
Yes, you should consider only those two options, do note that the number of arm/aarch64 downloads is *really* low compared to x86 tough and there might be important updates in the runtime update.

**Pull request merged**
