### PR TITLE
Update bitcoin-core to v0.19.0.1

### PR DESCRIPTION
**Pull request by A6GibKm**
The indentation was changed

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thanks, will review later today!

**Comment by MarcoFalke** [comment]
For some reason 32 bit was not picked up:

```
$ flatpak install --user https://dl.flathub.org/build-repo/11278/org.bitcoincore.bitcoin-qt.flatpakref 
error: No such ref 'app/org.bitcoincore.bitcoin-qt/i386/test' in remote bitcoin-qt-origin

**Comment by A6GibKm** [comment]
I noticed that the same did happen with the 0.18.1 build https://flathub.org/builds/#/builders/32/builds/9216

**Comment by A6GibKm** [comment]
@MarcoFalke the freedesktop 19.08 runtime doesn't support 32bit builds anymore, we could go back to 18.08 but have in mind that it will be deprecated in about a year.

**Pull request merged**
