### PR TITLE
Rework description

### PR DESCRIPTION
**Pull request by maflcko**
See https://github.com/bitcoin/bitcoin/commit/b8ded26ef3d7c58a938050659e4c50d850628dff

### CODE REVIEW

**Comment by MarcoFalke** [comment]
```
# flatpak info org.bitcoincore.bitcoin-qt 

Bitcoin Core - Fully validating Bitcoin peer-to-peer network node, wallet and
GUI

          ID: org.bitcoincore.bitcoin-qt
         Ref: app/org.bitcoincore.bitcoin-qt/x86_64/test
        Arch: x86_64
      Branch: test
     Version: 23.0
     License: MIT
      Origin: bitcoin-qt-origin
  Collection: org.flathub.Stable.Build88480
Installation: user
   Installed: 77.9 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 1e20dedc08a41785316db300fbd52dad59d1b3086d1e3bb7f1f7c1468f13457a
     Subject: Rework description (c5310257)
        Date: 2022-05-11 06:59:05 +0000

**Review by dunxen — APPROVED** [review]
ACK c531025

(Based on blurb change in README in https://github.com/bitcoin/bitcoin/commit/b8ded26ef3d7c58a938050659e4c50d850628dff)

**Review by josibake — APPROVED** [review]
ACK https://github.com/flathub/org.bitcoincore.bitcoin-qt/pull/20/commits/c5310257cfd59f6c330db989a276dbd5ed44c973

**Comment by MarcoFalke** [comment]
The files look flatpak-specific (at least partially), so I doubt there would be any benefit maintaining them upstream

**Comment by MarcoFalke** [comment]
I mean, improvements through pull requests welcome, if there is anything to improve.

**Comment by A6GibKm** [comment]
> I mean, improvements through pull requests welcome, if there is anything to improve.

Yeah, I will send a PR using the desktop file from upstream, it is new to me. 

Regarding the app id, the app id is the one used for DBus I think, but in any case it should not really matter if upstream just uses "Bitcoin Core" for example, I can ask around since I am not familiar with how the QT situation is regarding app IDs (which again is not a flatpak-only thing).

**Pull request merged**
