### PR TITLE
Update to 19.1

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK ddc4becfe655eadbc1a600b0fd80184b815f63c2

**Comment by MarcoFalke** [comment]
Will test in a bit

**Comment by A6GibKm** [comment]
Please do. The gui opens fine for me.

**Comment by sonky** [comment]
Hello i just started git hub site for now 
And i've some issues
Can i ask you for help

**Pull request merged**
